"""Синтетический профиль студента со стипендией и подработкой. Сентябрь 2026."""

DEMO_TODAY = "2026-09-26"

DEMO_TRANSACTIONS = [
    {
        "id": "t-901",
        "date": "2026-09-01",
        "amount": "-12000.00",
        "category": "rent",
        "merchant": "Аренда комнаты",
        "isRecurring": True,
    },
    {
        "id": "t-902",
        "date": "2026-09-02",
        "amount": "-299.00",
        "category": "subscriptions",
        "merchant": "Музыкальная подписка",
        "isRecurring": True,
    },
    {
        "id": "t-903",
        "date": "2026-09-02",
        "amount": "-649.00",
        "category": "subscriptions",
        "merchant": "Онлайн-кинотеатр",
        "isRecurring": True,
    },
    {
        "id": "t-904",
        "date": "2026-09-03",
        "amount": "-1450.00",
        "category": "food",
        "merchant": "Супермаркет",
        "isRecurring": False,
    },
    {
        "id": "t-905",
        "date": "2026-09-04",
        "amount": "-1200.00",
        "category": "transport",
        "merchant": "Проездной",
        "isRecurring": True,
    },
    {
        "id": "t-906",
        "date": "2026-09-05",
        "amount": "8000.00",
        "category": "other",
        "merchant": "Стипендия",
        "isRecurring": True,
    },
    {
        "id": "t-907",
        "date": "2026-09-06",
        "amount": "-780.00",
        "category": "entertainment",
        "merchant": "Кофейня",
        "isRecurring": False,
    },
    {
        "id": "t-908",
        "date": "2026-09-08",
        "amount": "-2300.00",
        "category": "food",
        "merchant": "Доставка еды",
        "isRecurring": False,
    },
    {
        "id": "t-909",
        "date": "2026-09-10",
        "amount": "25000.00",
        "category": "other",
        "merchant": "Подработка, аванс",
        "isRecurring": False,
    },
    {
        "id": "t-910",
        "date": "2026-09-11",
        "amount": "-450.00",
        "category": "health",
        "merchant": "Аптека",
        "isRecurring": False,
    },
    {
        "id": "t-911",
        "date": "2026-09-13",
        "amount": "-14900.00",
        "category": "entertainment",
        "merchant": "Концертные билеты",
        "isRecurring": False,
    },
    {
        "id": "t-912",
        "date": "2026-09-15",
        "amount": "-1890.00",
        "category": "food",
        "merchant": "Супермаркет",
        "isRecurring": False,
    },
    {
        "id": "t-913",
        "date": "2026-09-17",
        "amount": "-590.00",
        "category": "subscriptions",
        "merchant": "Мобильная связь",
        "isRecurring": True,
    },
    {
        "id": "t-914",
        "date": "2026-09-19",
        "amount": "-3200.00",
        "category": "education",
        "merchant": "Онлайн-курс",
        "isRecurring": False,
    },
    {
        "id": "t-915",
        "date": "2026-09-21",
        "amount": "-1120.00",
        "category": "food",
        "merchant": "Доставка еды",
        "isRecurring": False,
    },
    {
        "id": "t-916",
        "date": "2026-09-23",
        "amount": "-860.00",
        "category": "entertainment",
        "merchant": "Кофейня",
        "isRecurring": False,
    },
    {
        "id": "t-917",
        "date": "2026-09-25",
        "amount": "-240.00",
        "category": "transport",
        "merchant": "Такси",
        "isRecurring": False,
    },
    {
        "id": "t-801",
        "date": "2026-08-01",
        "amount": "-12000.00",
        "category": "rent",
        "merchant": "Аренда комнаты",
        "isRecurring": True,
    },
    {
        "id": "t-802",
        "date": "2026-08-02",
        "amount": "-299.00",
        "category": "subscriptions",
        "merchant": "Музыкальная подписка",
        "isRecurring": True,
    },
    {
        "id": "t-803",
        "date": "2026-08-05",
        "amount": "8000.00",
        "category": "other",
        "merchant": "Стипендия",
        "isRecurring": True,
    },
    {
        "id": "t-804",
        "date": "2026-08-07",
        "amount": "-4300.00",
        "category": "food",
        "merchant": "Супермаркет",
        "isRecurring": False,
    },
    {
        "id": "t-805",
        "date": "2026-08-12",
        "amount": "22000.00",
        "category": "other",
        "merchant": "Подработка",
        "isRecurring": False,
    },
    {
        "id": "t-806",
        "date": "2026-08-14",
        "amount": "-1600.00",
        "category": "entertainment",
        "merchant": "Кинотеатр",
        "isRecurring": False,
    },
    {
        "id": "t-807",
        "date": "2026-08-20",
        "amount": "-1200.00",
        "category": "transport",
        "merchant": "Проездной",
        "isRecurring": True,
    },
    {
        "id": "t-808",
        "date": "2026-08-26",
        "amount": "-2400.00",
        "category": "food",
        "merchant": "Доставка еды",
        "isRecurring": False,
    },
]

DEMO_INCOMES = [
    {"id": "i-1", "title": "Стипендия", "amount": "8000.00", "dayOfMonth": 5},
    {"id": "i-2", "title": "Подработка", "amount": "25000.00", "dayOfMonth": 10},
]

DEMO_GOALS = [
    {
        "id": "g-1",
        "title": "Ноутбук для учёбы",
        "targetAmount": "75000.00",
        "savedAmount": "21000.00",
        "deadline": "2027-02-01",
    },
    {
        "id": "g-2",
        "title": "Финансовая подушка",
        "targetAmount": "60000.00",
        "savedAmount": "3000.00",
        "deadline": None,
    },
]
